import 'package:youtube_explode_dart/youtube_explode_dart.dart';

import 'audio_track.dart';
import 'word_dictionary.dart';

/// Субтитры взять неоткуда: ссылка кривая, ролик удалён, закрыт, или у него
/// нет дорожки на нужном языке.
class CaptionsUnavailable implements Exception {
  final String reason;
  const CaptionsUnavailable(this.reason);

  @override
  String toString() => reason;
}

/// Субтитры ролика по ссылке — источник ПОСЛОВНОГО тайминга.
///
/// ЗАЧЕМ ИМЕННО АВТОМАТИЧЕСКИЕ. Ручные субтитры грамотнее, но размечены
/// строками: у целой строки одно время на все слова, и подсветка внутри
/// неё может только угадываться. Автоматические YouTube отдаёт разбитыми на
/// части, и у каждой части — своё смещение; это и есть время слова. Для
/// режима, который весь держится на «подсвечено ровно то, что звучит»,
/// разница решающая, поэтому автоматические здесь предпочтительнее.
///
/// СКАЧИВАЕТСЯ ТОЛЬКО ТЕКСТ. Медиа не трогаем: звук у трека свой, лежит в
/// самой игре.
class YoutubeCaptions {
  YoutubeCaptions._();

  /// Идентификатор ролика из ссылки любого вида (watch, youtu.be, shorts,
  /// embed) или сам идентификатор.
  ///
  /// Разбирает библиотека: форм ссылки больше, чем кажется, и своя
  /// регулярка ошибалась бы на каждой третьей.
  static String? videoIdFrom(String input) {
    final trimmed = input.trim();
    if (trimmed.isEmpty) return null;
    try {
      return VideoId.parseVideoId(trimmed) ?? VideoId(trimmed).value;
    } catch (_) {
      return null;
    }
  }

  /// Тянет субтитры и превращает их в строки трека.
  ///
  /// [dictionary] подставляет переводы из банка слов. Слова, которого в
  /// банке нет, остаются без перевода — см. WordDictionary.
  static Future<({List<TrackLine> lines, bool wordAccurate, String title})> fetch({
    required String videoId,
    required String language,
    WordDictionary? dictionary,
  }) async {
    final yt = YoutubeExplode();
    try {
      final video = await yt.videos.get(videoId).timeout(const Duration(seconds: 20));
      final manifest = await yt.videos.closedCaptions
          .getManifest(videoId)
          .timeout(const Duration(seconds: 20));

      // Сначала автоматические — ради пословного времени; ручные как
      // запасной вариант, лучше построчно, чем никак.
      final auto = manifest.getByLanguage(language, autoGenerated: true);
      final manual = manifest.getByLanguage(language);
      final info = (auto.isNotEmpty ? auto : manual).firstOrNull;
      if (info == null) {
        throw CaptionsUnavailable('у ролика нет субтитров на «$language»');
      }

      final track = await yt.videos.closedCaptions.get(info);
      final lines = <TrackLine>[];
      var wordAccurate = true;

      for (final caption in track.captions) {
        final start = caption.offset.inMilliseconds;
        final end = caption.end.inMilliseconds;
        final parts = caption.parts;
        final words = <TimedWord>[];

        if (parts.isNotEmpty) {
          for (var i = 0; i < parts.length; i++) {
            final text = parts[i].text.trim();
            if (text.isEmpty) continue;
            final from = start + parts[i].offset.inMilliseconds;
            final to = i + 1 < parts.length
                ? start + parts[i + 1].offset.inMilliseconds
                : end;
            words.add(_word(text, from, to, dictionary));
          }
        } else {
          // Пословного времени нет — делим строку пропорционально длине
          // слов. Это приближение, и инструмент говорит об этом прямо.
          wordAccurate = false;
          final raw = caption.text
              .split(RegExp(r'\s+'))
              .where((w) => w.trim().isNotEmpty)
              .toList();
          final letters = raw.fold<int>(0, (sum, w) => sum + w.length);
          if (letters == 0) continue;
          var cursor = start;
          for (var i = 0; i < raw.length; i++) {
            final share = ((end - start) * raw[i].length / letters).round();
            final to = i == raw.length - 1 ? end : cursor + share;
            words.add(_word(raw[i].trim(), cursor, to, dictionary));
            cursor = to;
          }
        }

        if (words.isNotEmpty) lines.add(TrackLine(words));
      }

      if (lines.isEmpty) throw const CaptionsUnavailable('субтитры пустые');
      return (lines: lines, wordAccurate: wordAccurate, title: video.title);
    } on CaptionsUnavailable {
      rethrow;
    } catch (e) {
      throw CaptionsUnavailable('$e');
    } finally {
      yt.close();
    }
  }

  static TimedWord _word(String text, int from, int to, WordDictionary? dictionary) =>
      TimedWord(
        text: text,
        translation: dictionary?.translate(text),
        startMs: from,
        // Слово не может кончиться раньше, чем началось: у кривых субтитров
        // соседние реплики иногда перекрываются.
        endMs: to > from ? to : from + 1,
      );
}
